"""Emit the game CSS for every pixel asset, read off the assets themselves.

Frame counts and sheet geometry are properties of the PNGs, so they are read
from the generators rather than restated in the stylesheet: a hand-written
`steps(8)` beside a six-frame sheet is a bug nobody notices until the
animation stutters.

Usage: python3 tools/pixelart/emit_css.py > /tmp/pixel.css
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from devices import DEV
from sprites import CAST, FACINGS

# Seconds per cycle. A furnace breathes; a rolling mill does not, and a mill
# that spins fast reads as dangerous rather than busy.
SPEED = {'furnace': 1.6, 'casting': 1.4, 'om': 1.8, 'pc': 1.6, 'arc': 0.9,
         'rolling': 1.9, 'sem': 1.2, 'laser': 1.1, 'magnet': 1.3, 'tem': 1.8,
         'phase': 1.4, 'qaa': 1.0, 'agt': 1.2, 'mpss': 2.0}

out = []
w = out.append

w("""  /* =============================================================
     PIXEL ART — GENERATED by tools/pixelart/emit_css.py.
     Edit the generator, not this block.

     One art pixel is 1/16 of a lab tile, so every sprite is drawn at exactly
     its own footprint and needs no per-device correction. Sheets lay their
     frames out side by side and are stepped with `steps(n, jump-none)`,
     which is the one timing function that lands on every frame including the
     last: with a sheet n times the box width, position 0%..100% maps to
     offsets 0..-(n-1) box widths, and jump-none divides that into n-1 hops.
     ============================================================= */

  /* --- devices ------------------------------------------------- */""")
for did in sorted(DEV):
    n = DEV[did][3]
    w("  .equip[data-id^=\"%s\"] .eq-sprite { background-image: url('assets/pixel/anim/%s.png');"
      " --fr: %d; }" % (did, did, n))
w("")
w("""  /* Idle devices hold frame 0 and cost nothing; the sheet only runs while
     the device is working, which is the contract the old overlay effects
     had too. */""")
for did in sorted(DEV):
    n, secs = DEV[did][3], SPEED[did]
    w("  .equip.busy:not(.broken)[data-id^=\"%s\"] .eq-sprite"
      " { animation: eqrun %.1fs steps(%d, jump-none) infinite; }" % (did, secs, n))
w("")
w("  @keyframes eqrun { to { background-position-x: 100%; } }")
w("")
w("""  /* --- lab-floor characters ------------------------------------
     One sheet per person: three facings across, two walk frames down. `side`
     is drawn facing right and mirrored in CSS for left, which the symmetric
     projection makes free. */""")
w("  .character[data-face=\"side\"] { background-position-x: 50%; }")
w("  .character[data-face=\"back\"] { background-position-x: 100%; }")
w("  .character.walking { animation: cw-step 0.34s steps(2, jump-none) infinite; }")
w("  @keyframes cw-step { to { background-position-y: 100%; } }")
w("")
for cid in CAST:
    w("  .character[data-cw=\"%s\"] { background-image: url('assets/pixel/char/%s.png'); }"
      % (cid, cid))
w("")
w("""  /* --- the room ------------------------------------------------
     Floor tiles are 32px, two lab tiles square: a pattern that repeats every
     tile beats in time with the grid and reads as wallpaper.

     Of the four walls only the far one shows a face in this projection, so it
     is the only one carrying art; left, right and near are edge-on and are
     bands of colour. What is behind the glass follows the in-game clock. */""")
from walls import SIDE, DOOR
for lv in (1, 2, 3, 4):
    w("  .lab[data-lv=\"%d\"] { --floor: url('assets/pixel/floor/lv%d.png');"
      " --wall-side: %s; --wall-door: %s; }" % (lv, lv, SIDE[lv], DOOR[lv]))
w("")
for lv in (1, 2, 3, 4):
    for tod in ('day', 'night'):
        w("  .lab[data-lv=\"%d\"][data-time=\"%s\"] .w-top"
          " { background-image: url('assets/pixel/wall/top_lv%d_%s.png'); }"
          % (lv, tod, lv, tod))

print('\n'.join(out))
